// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: youliao.login.proto

#include "youliao.login.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace youliao {
namespace pdu {
namespace login {
class MsgServerRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgServerRequest>
      _instance;
} _MsgServerRequest_default_instance_;
class MsgServerResponeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgServerRespone>
      _instance;
} _MsgServerRespone_default_instance_;
}  // namespace login
}  // namespace pdu
}  // namespace youliao
namespace protobuf_youliao_2elogin_2eproto {
void InitDefaultsMsgServerRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::youliao::pdu::login::_MsgServerRequest_default_instance_;
    new (ptr) ::youliao::pdu::login::MsgServerRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::youliao::pdu::login::MsgServerRequest::InitAsDefaultInstance();
}

void InitDefaultsMsgServerRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMsgServerRequestImpl);
}

void InitDefaultsMsgServerResponeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::youliao::pdu::login::_MsgServerRespone_default_instance_;
    new (ptr) ::youliao::pdu::login::MsgServerRespone();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::youliao::pdu::login::MsgServerRespone::InitAsDefaultInstance();
}

void InitDefaultsMsgServerRespone() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMsgServerResponeImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::login::MsgServerRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::login::MsgServerRespone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::login::MsgServerRespone, result_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::login::MsgServerRespone, msg_server_ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::login::MsgServerRespone, port_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::youliao::pdu::login::MsgServerRequest)},
  { 5, -1, sizeof(::youliao::pdu::login::MsgServerRespone)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::youliao::pdu::login::_MsgServerRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::youliao::pdu::login::_MsgServerRespone_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "youliao.login.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023youliao.login.proto\022\021youliao.pdu.login"
      "\032\022youliao.base.proto\"\022\n\020MsgServerRequest"
      "\"j\n\020MsgServerRespone\0221\n\013result_code\030\001 \001("
      "\0162\034.youliao.pdu.base.ResultType\022\025\n\rmsg_s"
      "erver_ip\030\002 \001(\t\022\014\n\004port\030\003 \001(\rb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 196);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "youliao.login.proto", &protobuf_RegisterTypes);
  ::protobuf_youliao_2ebase_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_youliao_2elogin_2eproto
namespace youliao {
namespace pdu {
namespace login {

// ===================================================================

void MsgServerRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgServerRequest::MsgServerRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_youliao_2elogin_2eproto::InitDefaultsMsgServerRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:youliao.pdu.login.MsgServerRequest)
}
MsgServerRequest::MsgServerRequest(const MsgServerRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:youliao.pdu.login.MsgServerRequest)
}

void MsgServerRequest::SharedCtor() {
  _cached_size_ = 0;
}

MsgServerRequest::~MsgServerRequest() {
  // @@protoc_insertion_point(destructor:youliao.pdu.login.MsgServerRequest)
  SharedDtor();
}

void MsgServerRequest::SharedDtor() {
}

void MsgServerRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgServerRequest::descriptor() {
  ::protobuf_youliao_2elogin_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2elogin_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgServerRequest& MsgServerRequest::default_instance() {
  ::protobuf_youliao_2elogin_2eproto::InitDefaultsMsgServerRequest();
  return *internal_default_instance();
}

MsgServerRequest* MsgServerRequest::New(::google::protobuf::Arena* arena) const {
  MsgServerRequest* n = new MsgServerRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgServerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:youliao.pdu.login.MsgServerRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool MsgServerRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:youliao.pdu.login.MsgServerRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:youliao.pdu.login.MsgServerRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:youliao.pdu.login.MsgServerRequest)
  return false;
#undef DO_
}

void MsgServerRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:youliao.pdu.login.MsgServerRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:youliao.pdu.login.MsgServerRequest)
}

::google::protobuf::uint8* MsgServerRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:youliao.pdu.login.MsgServerRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:youliao.pdu.login.MsgServerRequest)
  return target;
}

size_t MsgServerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:youliao.pdu.login.MsgServerRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgServerRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:youliao.pdu.login.MsgServerRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgServerRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgServerRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:youliao.pdu.login.MsgServerRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:youliao.pdu.login.MsgServerRequest)
    MergeFrom(*source);
  }
}

void MsgServerRequest::MergeFrom(const MsgServerRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:youliao.pdu.login.MsgServerRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void MsgServerRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:youliao.pdu.login.MsgServerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgServerRequest::CopyFrom(const MsgServerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:youliao.pdu.login.MsgServerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgServerRequest::IsInitialized() const {
  return true;
}

void MsgServerRequest::Swap(MsgServerRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgServerRequest::InternalSwap(MsgServerRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgServerRequest::GetMetadata() const {
  protobuf_youliao_2elogin_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2elogin_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MsgServerRespone::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgServerRespone::kResultCodeFieldNumber;
const int MsgServerRespone::kMsgServerIpFieldNumber;
const int MsgServerRespone::kPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgServerRespone::MsgServerRespone()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_youliao_2elogin_2eproto::InitDefaultsMsgServerRespone();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:youliao.pdu.login.MsgServerRespone)
}
MsgServerRespone::MsgServerRespone(const MsgServerRespone& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  msg_server_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg_server_ip().size() > 0) {
    msg_server_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_server_ip_);
  }
  ::memcpy(&result_code_, &from.result_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&port_) -
    reinterpret_cast<char*>(&result_code_)) + sizeof(port_));
  // @@protoc_insertion_point(copy_constructor:youliao.pdu.login.MsgServerRespone)
}

void MsgServerRespone::SharedCtor() {
  msg_server_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&result_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&port_) -
      reinterpret_cast<char*>(&result_code_)) + sizeof(port_));
  _cached_size_ = 0;
}

MsgServerRespone::~MsgServerRespone() {
  // @@protoc_insertion_point(destructor:youliao.pdu.login.MsgServerRespone)
  SharedDtor();
}

void MsgServerRespone::SharedDtor() {
  msg_server_ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MsgServerRespone::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgServerRespone::descriptor() {
  ::protobuf_youliao_2elogin_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2elogin_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgServerRespone& MsgServerRespone::default_instance() {
  ::protobuf_youliao_2elogin_2eproto::InitDefaultsMsgServerRespone();
  return *internal_default_instance();
}

MsgServerRespone* MsgServerRespone::New(::google::protobuf::Arena* arena) const {
  MsgServerRespone* n = new MsgServerRespone;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgServerRespone::Clear() {
// @@protoc_insertion_point(message_clear_start:youliao.pdu.login.MsgServerRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_server_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&result_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&port_) -
      reinterpret_cast<char*>(&result_code_)) + sizeof(port_));
  _internal_metadata_.Clear();
}

bool MsgServerRespone::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:youliao.pdu.login.MsgServerRespone)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .youliao.pdu.base.ResultType result_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_result_code(static_cast< ::youliao::pdu::base::ResultType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msg_server_ip = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg_server_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg_server_ip().data(), static_cast<int>(this->msg_server_ip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "youliao.pdu.login.MsgServerRespone.msg_server_ip"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 port = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:youliao.pdu.login.MsgServerRespone)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:youliao.pdu.login.MsgServerRespone)
  return false;
#undef DO_
}

void MsgServerRespone::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:youliao.pdu.login.MsgServerRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .youliao.pdu.base.ResultType result_code = 1;
  if (this->result_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->result_code(), output);
  }

  // string msg_server_ip = 2;
  if (this->msg_server_ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg_server_ip().data(), static_cast<int>(this->msg_server_ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "youliao.pdu.login.MsgServerRespone.msg_server_ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->msg_server_ip(), output);
  }

  // uint32 port = 3;
  if (this->port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->port(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:youliao.pdu.login.MsgServerRespone)
}

::google::protobuf::uint8* MsgServerRespone::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:youliao.pdu.login.MsgServerRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .youliao.pdu.base.ResultType result_code = 1;
  if (this->result_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->result_code(), target);
  }

  // string msg_server_ip = 2;
  if (this->msg_server_ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg_server_ip().data(), static_cast<int>(this->msg_server_ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "youliao.pdu.login.MsgServerRespone.msg_server_ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->msg_server_ip(), target);
  }

  // uint32 port = 3;
  if (this->port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->port(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:youliao.pdu.login.MsgServerRespone)
  return target;
}

size_t MsgServerRespone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:youliao.pdu.login.MsgServerRespone)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string msg_server_ip = 2;
  if (this->msg_server_ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg_server_ip());
  }

  // .youliao.pdu.base.ResultType result_code = 1;
  if (this->result_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->result_code());
  }

  // uint32 port = 3;
  if (this->port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->port());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgServerRespone::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:youliao.pdu.login.MsgServerRespone)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgServerRespone* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgServerRespone>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:youliao.pdu.login.MsgServerRespone)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:youliao.pdu.login.MsgServerRespone)
    MergeFrom(*source);
  }
}

void MsgServerRespone::MergeFrom(const MsgServerRespone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:youliao.pdu.login.MsgServerRespone)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg_server_ip().size() > 0) {

    msg_server_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_server_ip_);
  }
  if (from.result_code() != 0) {
    set_result_code(from.result_code());
  }
  if (from.port() != 0) {
    set_port(from.port());
  }
}

void MsgServerRespone::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:youliao.pdu.login.MsgServerRespone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgServerRespone::CopyFrom(const MsgServerRespone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:youliao.pdu.login.MsgServerRespone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgServerRespone::IsInitialized() const {
  return true;
}

void MsgServerRespone::Swap(MsgServerRespone* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgServerRespone::InternalSwap(MsgServerRespone* other) {
  using std::swap;
  msg_server_ip_.Swap(&other->msg_server_ip_);
  swap(result_code_, other->result_code_);
  swap(port_, other->port_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgServerRespone::GetMetadata() const {
  protobuf_youliao_2elogin_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2elogin_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace login
}  // namespace pdu
}  // namespace youliao

// @@protoc_insertion_point(global_scope)
