// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: youliao.group.proto

#include "youliao.group.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace youliao {
namespace pdu {
namespace group {
class GroupCreateRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GroupCreateRequest>
      _instance;
} _GroupCreateRequest_default_instance_;
class GroupCreateResponeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GroupCreateRespone>
      _instance;
} _GroupCreateRespone_default_instance_;
class GetGroupListRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetGroupListRequest>
      _instance;
} _GetGroupListRequest_default_instance_;
class GetGroupListResponeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetGroupListRespone>
      _instance;
} _GetGroupListRespone_default_instance_;
}  // namespace group
}  // namespace pdu
}  // namespace youliao
namespace protobuf_youliao_2egroup_2eproto {
void InitDefaultsGroupCreateRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::youliao::pdu::group::_GroupCreateRequest_default_instance_;
    new (ptr) ::youliao::pdu::group::GroupCreateRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::youliao::pdu::group::GroupCreateRequest::InitAsDefaultInstance();
}

void InitDefaultsGroupCreateRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGroupCreateRequestImpl);
}

void InitDefaultsGroupCreateResponeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_youliao_2ebase_2eproto::InitDefaultsGroupInfo();
  {
    void* ptr = &::youliao::pdu::group::_GroupCreateRespone_default_instance_;
    new (ptr) ::youliao::pdu::group::GroupCreateRespone();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::youliao::pdu::group::GroupCreateRespone::InitAsDefaultInstance();
}

void InitDefaultsGroupCreateRespone() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGroupCreateResponeImpl);
}

void InitDefaultsGetGroupListRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::youliao::pdu::group::_GetGroupListRequest_default_instance_;
    new (ptr) ::youliao::pdu::group::GetGroupListRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::youliao::pdu::group::GetGroupListRequest::InitAsDefaultInstance();
}

void InitDefaultsGetGroupListRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetGroupListRequestImpl);
}

void InitDefaultsGetGroupListResponeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_youliao_2ebase_2eproto::InitDefaultsGroupInfo();
  {
    void* ptr = &::youliao::pdu::group::_GetGroupListRespone_default_instance_;
    new (ptr) ::youliao::pdu::group::GetGroupListRespone();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::youliao::pdu::group::GetGroupListRespone::InitAsDefaultInstance();
}

void InitDefaultsGetGroupListRespone() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetGroupListResponeImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, group_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, group_head_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, group_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, group_verify_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, member_ids_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRequest, group_max_members_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRespone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRespone, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRespone, result_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GroupCreateRespone, group_info_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GetGroupListRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GetGroupListRequest, user_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GetGroupListRespone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GetGroupListRespone, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::youliao::pdu::group::GetGroupListRespone, group_info_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::youliao::pdu::group::GroupCreateRequest)},
  { 12, -1, sizeof(::youliao::pdu::group::GroupCreateRespone)},
  { 20, -1, sizeof(::youliao::pdu::group::GetGroupListRequest)},
  { 26, -1, sizeof(::youliao::pdu::group::GetGroupListRespone)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::youliao::pdu::group::_GroupCreateRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::youliao::pdu::group::_GroupCreateRespone_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::youliao::pdu::group::_GetGroupListRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::youliao::pdu::group::_GetGroupListRespone_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "youliao.group.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023youliao.group.proto\022\021youliao.pdu.group"
      "\032\022youliao.base.proto\"\353\001\n\022GroupCreateRequ"
      "est\022\017\n\007user_id\030\001 \001(\r\022\022\n\ngroup_name\030\002 \001(\t"
      "\022\022\n\ngroup_head\030\003 \001(\t\022/\n\ngroup_type\030\004 \001(\016"
      "2\033.youliao.pdu.base.GroupType\022<\n\021group_v"
      "erify_type\030\005 \001(\0162!.youliao.pdu.base.Grou"
      "pVerifyType\022\022\n\nmember_ids\030\006 \003(\r\022\031\n\021group"
      "_max_members\030\007 \001(\r\"k\n\022GroupCreateRespone"
      "\022\017\n\007user_id\030\001 \001(\r\022\023\n\013result_code\030\002 \001(\r\022/"
      "\n\ngroup_info\030\003 \001(\0132\033.youliao.pdu.base.Gr"
      "oupInfo\"&\n\023GetGroupListRequest\022\017\n\007user_i"
      "d\030\001 \001(\r\"W\n\023GetGroupListRespone\022\017\n\007user_i"
      "d\030\001 \001(\r\022/\n\ngroup_info\030\002 \003(\0132\033.youliao.pd"
      "u.base.GroupInfob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 544);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "youliao.group.proto", &protobuf_RegisterTypes);
  ::protobuf_youliao_2ebase_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_youliao_2egroup_2eproto
namespace youliao {
namespace pdu {
namespace group {

// ===================================================================

void GroupCreateRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GroupCreateRequest::kUserIdFieldNumber;
const int GroupCreateRequest::kGroupNameFieldNumber;
const int GroupCreateRequest::kGroupHeadFieldNumber;
const int GroupCreateRequest::kGroupTypeFieldNumber;
const int GroupCreateRequest::kGroupVerifyTypeFieldNumber;
const int GroupCreateRequest::kMemberIdsFieldNumber;
const int GroupCreateRequest::kGroupMaxMembersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GroupCreateRequest::GroupCreateRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_youliao_2egroup_2eproto::InitDefaultsGroupCreateRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:youliao.pdu.group.GroupCreateRequest)
}
GroupCreateRequest::GroupCreateRequest(const GroupCreateRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      member_ids_(from.member_ids_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  group_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.group_name().size() > 0) {
    group_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.group_name_);
  }
  group_head_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.group_head().size() > 0) {
    group_head_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.group_head_);
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&group_max_members_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(group_max_members_));
  // @@protoc_insertion_point(copy_constructor:youliao.pdu.group.GroupCreateRequest)
}

void GroupCreateRequest::SharedCtor() {
  group_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  group_head_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&group_max_members_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(group_max_members_));
  _cached_size_ = 0;
}

GroupCreateRequest::~GroupCreateRequest() {
  // @@protoc_insertion_point(destructor:youliao.pdu.group.GroupCreateRequest)
  SharedDtor();
}

void GroupCreateRequest::SharedDtor() {
  group_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  group_head_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GroupCreateRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GroupCreateRequest::descriptor() {
  ::protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GroupCreateRequest& GroupCreateRequest::default_instance() {
  ::protobuf_youliao_2egroup_2eproto::InitDefaultsGroupCreateRequest();
  return *internal_default_instance();
}


void GroupCreateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:youliao.pdu.group.GroupCreateRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  member_ids_.Clear();
  group_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  group_head_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&group_max_members_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(group_max_members_));
  _internal_metadata_.Clear();
}

bool GroupCreateRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:youliao.pdu.group.GroupCreateRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string group_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_group_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->group_name().data(), static_cast<int>(this->group_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "youliao.pdu.group.GroupCreateRequest.group_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string group_head = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_group_head()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->group_head().data(), static_cast<int>(this->group_head().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "youliao.pdu.group.GroupCreateRequest.group_head"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .youliao.pdu.base.GroupType group_type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_group_type(static_cast< ::youliao::pdu::base::GroupType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .youliao.pdu.base.GroupVerifyType group_verify_type = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_group_verify_type(static_cast< ::youliao::pdu::base::GroupVerifyType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 member_ids = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_member_ids())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 50u, input, this->mutable_member_ids())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 group_max_members = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &group_max_members_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:youliao.pdu.group.GroupCreateRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:youliao.pdu.group.GroupCreateRequest)
  return false;
#undef DO_
}

void GroupCreateRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:youliao.pdu.group.GroupCreateRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // string group_name = 2;
  if (this->group_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->group_name().data(), static_cast<int>(this->group_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "youliao.pdu.group.GroupCreateRequest.group_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->group_name(), output);
  }

  // string group_head = 3;
  if (this->group_head().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->group_head().data(), static_cast<int>(this->group_head().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "youliao.pdu.group.GroupCreateRequest.group_head");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->group_head(), output);
  }

  // .youliao.pdu.base.GroupType group_type = 4;
  if (this->group_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->group_type(), output);
  }

  // .youliao.pdu.base.GroupVerifyType group_verify_type = 5;
  if (this->group_verify_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->group_verify_type(), output);
  }

  // repeated uint32 member_ids = 6;
  if (this->member_ids_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _member_ids_cached_byte_size_));
  }
  for (int i = 0, n = this->member_ids_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->member_ids(i), output);
  }

  // uint32 group_max_members = 7;
  if (this->group_max_members() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->group_max_members(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:youliao.pdu.group.GroupCreateRequest)
}

::google::protobuf::uint8* GroupCreateRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:youliao.pdu.group.GroupCreateRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // string group_name = 2;
  if (this->group_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->group_name().data(), static_cast<int>(this->group_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "youliao.pdu.group.GroupCreateRequest.group_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->group_name(), target);
  }

  // string group_head = 3;
  if (this->group_head().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->group_head().data(), static_cast<int>(this->group_head().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "youliao.pdu.group.GroupCreateRequest.group_head");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->group_head(), target);
  }

  // .youliao.pdu.base.GroupType group_type = 4;
  if (this->group_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->group_type(), target);
  }

  // .youliao.pdu.base.GroupVerifyType group_verify_type = 5;
  if (this->group_verify_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->group_verify_type(), target);
  }

  // repeated uint32 member_ids = 6;
  if (this->member_ids_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _member_ids_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->member_ids_, target);
  }

  // uint32 group_max_members = 7;
  if (this->group_max_members() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->group_max_members(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:youliao.pdu.group.GroupCreateRequest)
  return target;
}

size_t GroupCreateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:youliao.pdu.group.GroupCreateRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated uint32 member_ids = 6;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->member_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _member_ids_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string group_name = 2;
  if (this->group_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->group_name());
  }

  // string group_head = 3;
  if (this->group_head().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->group_head());
  }

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->user_id());
  }

  // .youliao.pdu.base.GroupType group_type = 4;
  if (this->group_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->group_type());
  }

  // .youliao.pdu.base.GroupVerifyType group_verify_type = 5;
  if (this->group_verify_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->group_verify_type());
  }

  // uint32 group_max_members = 7;
  if (this->group_max_members() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->group_max_members());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GroupCreateRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:youliao.pdu.group.GroupCreateRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GroupCreateRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GroupCreateRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:youliao.pdu.group.GroupCreateRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:youliao.pdu.group.GroupCreateRequest)
    MergeFrom(*source);
  }
}

void GroupCreateRequest::MergeFrom(const GroupCreateRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:youliao.pdu.group.GroupCreateRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  member_ids_.MergeFrom(from.member_ids_);
  if (from.group_name().size() > 0) {

    group_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.group_name_);
  }
  if (from.group_head().size() > 0) {

    group_head_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.group_head_);
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.group_type() != 0) {
    set_group_type(from.group_type());
  }
  if (from.group_verify_type() != 0) {
    set_group_verify_type(from.group_verify_type());
  }
  if (from.group_max_members() != 0) {
    set_group_max_members(from.group_max_members());
  }
}

void GroupCreateRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:youliao.pdu.group.GroupCreateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GroupCreateRequest::CopyFrom(const GroupCreateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:youliao.pdu.group.GroupCreateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroupCreateRequest::IsInitialized() const {
  return true;
}

void GroupCreateRequest::Swap(GroupCreateRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GroupCreateRequest::InternalSwap(GroupCreateRequest* other) {
  using std::swap;
  member_ids_.InternalSwap(&other->member_ids_);
  group_name_.Swap(&other->group_name_);
  group_head_.Swap(&other->group_head_);
  swap(user_id_, other->user_id_);
  swap(group_type_, other->group_type_);
  swap(group_verify_type_, other->group_verify_type_);
  swap(group_max_members_, other->group_max_members_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GroupCreateRequest::GetMetadata() const {
  protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GroupCreateRespone::InitAsDefaultInstance() {
  ::youliao::pdu::group::_GroupCreateRespone_default_instance_._instance.get_mutable()->group_info_ = const_cast< ::youliao::pdu::base::GroupInfo*>(
      ::youliao::pdu::base::GroupInfo::internal_default_instance());
}
void GroupCreateRespone::clear_group_info() {
  if (GetArenaNoVirtual() == NULL && group_info_ != NULL) {
    delete group_info_;
  }
  group_info_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GroupCreateRespone::kUserIdFieldNumber;
const int GroupCreateRespone::kResultCodeFieldNumber;
const int GroupCreateRespone::kGroupInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GroupCreateRespone::GroupCreateRespone()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_youliao_2egroup_2eproto::InitDefaultsGroupCreateRespone();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:youliao.pdu.group.GroupCreateRespone)
}
GroupCreateRespone::GroupCreateRespone(const GroupCreateRespone& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_group_info()) {
    group_info_ = new ::youliao::pdu::base::GroupInfo(*from.group_info_);
  } else {
    group_info_ = NULL;
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&result_code_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(result_code_));
  // @@protoc_insertion_point(copy_constructor:youliao.pdu.group.GroupCreateRespone)
}

void GroupCreateRespone::SharedCtor() {
  ::memset(&group_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&result_code_) -
      reinterpret_cast<char*>(&group_info_)) + sizeof(result_code_));
  _cached_size_ = 0;
}

GroupCreateRespone::~GroupCreateRespone() {
  // @@protoc_insertion_point(destructor:youliao.pdu.group.GroupCreateRespone)
  SharedDtor();
}

void GroupCreateRespone::SharedDtor() {
  if (this != internal_default_instance()) delete group_info_;
}

void GroupCreateRespone::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GroupCreateRespone::descriptor() {
  ::protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GroupCreateRespone& GroupCreateRespone::default_instance() {
  ::protobuf_youliao_2egroup_2eproto::InitDefaultsGroupCreateRespone();
  return *internal_default_instance();
}


void GroupCreateRespone::Clear() {
// @@protoc_insertion_point(message_clear_start:youliao.pdu.group.GroupCreateRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && group_info_ != NULL) {
    delete group_info_;
  }
  group_info_ = NULL;
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&result_code_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(result_code_));
  _internal_metadata_.Clear();
}

bool GroupCreateRespone::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:youliao.pdu.group.GroupCreateRespone)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 result_code = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &result_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .youliao.pdu.base.GroupInfo group_info = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_group_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:youliao.pdu.group.GroupCreateRespone)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:youliao.pdu.group.GroupCreateRespone)
  return false;
#undef DO_
}

void GroupCreateRespone::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:youliao.pdu.group.GroupCreateRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // uint32 result_code = 2;
  if (this->result_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->result_code(), output);
  }

  // .youliao.pdu.base.GroupInfo group_info = 3;
  if (this->has_group_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *group_info_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:youliao.pdu.group.GroupCreateRespone)
}

::google::protobuf::uint8* GroupCreateRespone::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:youliao.pdu.group.GroupCreateRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // uint32 result_code = 2;
  if (this->result_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->result_code(), target);
  }

  // .youliao.pdu.base.GroupInfo group_info = 3;
  if (this->has_group_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *group_info_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:youliao.pdu.group.GroupCreateRespone)
  return target;
}

size_t GroupCreateRespone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:youliao.pdu.group.GroupCreateRespone)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .youliao.pdu.base.GroupInfo group_info = 3;
  if (this->has_group_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *group_info_);
  }

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->user_id());
  }

  // uint32 result_code = 2;
  if (this->result_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->result_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GroupCreateRespone::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:youliao.pdu.group.GroupCreateRespone)
  GOOGLE_DCHECK_NE(&from, this);
  const GroupCreateRespone* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GroupCreateRespone>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:youliao.pdu.group.GroupCreateRespone)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:youliao.pdu.group.GroupCreateRespone)
    MergeFrom(*source);
  }
}

void GroupCreateRespone::MergeFrom(const GroupCreateRespone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:youliao.pdu.group.GroupCreateRespone)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_group_info()) {
    mutable_group_info()->::youliao::pdu::base::GroupInfo::MergeFrom(from.group_info());
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.result_code() != 0) {
    set_result_code(from.result_code());
  }
}

void GroupCreateRespone::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:youliao.pdu.group.GroupCreateRespone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GroupCreateRespone::CopyFrom(const GroupCreateRespone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:youliao.pdu.group.GroupCreateRespone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroupCreateRespone::IsInitialized() const {
  return true;
}

void GroupCreateRespone::Swap(GroupCreateRespone* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GroupCreateRespone::InternalSwap(GroupCreateRespone* other) {
  using std::swap;
  swap(group_info_, other->group_info_);
  swap(user_id_, other->user_id_);
  swap(result_code_, other->result_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GroupCreateRespone::GetMetadata() const {
  protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetGroupListRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetGroupListRequest::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetGroupListRequest::GetGroupListRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_youliao_2egroup_2eproto::InitDefaultsGetGroupListRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:youliao.pdu.group.GetGroupListRequest)
}
GetGroupListRequest::GetGroupListRequest(const GetGroupListRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_id_ = from.user_id_;
  // @@protoc_insertion_point(copy_constructor:youliao.pdu.group.GetGroupListRequest)
}

void GetGroupListRequest::SharedCtor() {
  user_id_ = 0u;
  _cached_size_ = 0;
}

GetGroupListRequest::~GetGroupListRequest() {
  // @@protoc_insertion_point(destructor:youliao.pdu.group.GetGroupListRequest)
  SharedDtor();
}

void GetGroupListRequest::SharedDtor() {
}

void GetGroupListRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetGroupListRequest::descriptor() {
  ::protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetGroupListRequest& GetGroupListRequest::default_instance() {
  ::protobuf_youliao_2egroup_2eproto::InitDefaultsGetGroupListRequest();
  return *internal_default_instance();
}


void GetGroupListRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:youliao.pdu.group.GetGroupListRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  user_id_ = 0u;
  _internal_metadata_.Clear();
}

bool GetGroupListRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:youliao.pdu.group.GetGroupListRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:youliao.pdu.group.GetGroupListRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:youliao.pdu.group.GetGroupListRequest)
  return false;
#undef DO_
}

void GetGroupListRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:youliao.pdu.group.GetGroupListRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:youliao.pdu.group.GetGroupListRequest)
}

::google::protobuf::uint8* GetGroupListRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:youliao.pdu.group.GetGroupListRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:youliao.pdu.group.GetGroupListRequest)
  return target;
}

size_t GetGroupListRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:youliao.pdu.group.GetGroupListRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->user_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetGroupListRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:youliao.pdu.group.GetGroupListRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetGroupListRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetGroupListRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:youliao.pdu.group.GetGroupListRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:youliao.pdu.group.GetGroupListRequest)
    MergeFrom(*source);
  }
}

void GetGroupListRequest::MergeFrom(const GetGroupListRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:youliao.pdu.group.GetGroupListRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
}

void GetGroupListRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:youliao.pdu.group.GetGroupListRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetGroupListRequest::CopyFrom(const GetGroupListRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:youliao.pdu.group.GetGroupListRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetGroupListRequest::IsInitialized() const {
  return true;
}

void GetGroupListRequest::Swap(GetGroupListRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetGroupListRequest::InternalSwap(GetGroupListRequest* other) {
  using std::swap;
  swap(user_id_, other->user_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetGroupListRequest::GetMetadata() const {
  protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetGroupListRespone::InitAsDefaultInstance() {
}
void GetGroupListRespone::clear_group_info() {
  group_info_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetGroupListRespone::kUserIdFieldNumber;
const int GetGroupListRespone::kGroupInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetGroupListRespone::GetGroupListRespone()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_youliao_2egroup_2eproto::InitDefaultsGetGroupListRespone();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:youliao.pdu.group.GetGroupListRespone)
}
GetGroupListRespone::GetGroupListRespone(const GetGroupListRespone& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      group_info_(from.group_info_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_id_ = from.user_id_;
  // @@protoc_insertion_point(copy_constructor:youliao.pdu.group.GetGroupListRespone)
}

void GetGroupListRespone::SharedCtor() {
  user_id_ = 0u;
  _cached_size_ = 0;
}

GetGroupListRespone::~GetGroupListRespone() {
  // @@protoc_insertion_point(destructor:youliao.pdu.group.GetGroupListRespone)
  SharedDtor();
}

void GetGroupListRespone::SharedDtor() {
}

void GetGroupListRespone::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetGroupListRespone::descriptor() {
  ::protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetGroupListRespone& GetGroupListRespone::default_instance() {
  ::protobuf_youliao_2egroup_2eproto::InitDefaultsGetGroupListRespone();
  return *internal_default_instance();
}


void GetGroupListRespone::Clear() {
// @@protoc_insertion_point(message_clear_start:youliao.pdu.group.GetGroupListRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  group_info_.Clear();
  user_id_ = 0u;
  _internal_metadata_.Clear();
}

bool GetGroupListRespone::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:youliao.pdu.group.GetGroupListRespone)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .youliao.pdu.base.GroupInfo group_info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_group_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:youliao.pdu.group.GetGroupListRespone)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:youliao.pdu.group.GetGroupListRespone)
  return false;
#undef DO_
}

void GetGroupListRespone::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:youliao.pdu.group.GetGroupListRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // repeated .youliao.pdu.base.GroupInfo group_info = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->group_info_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->group_info(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:youliao.pdu.group.GetGroupListRespone)
}

::google::protobuf::uint8* GetGroupListRespone::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:youliao.pdu.group.GetGroupListRespone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // repeated .youliao.pdu.base.GroupInfo group_info = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->group_info_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->group_info(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:youliao.pdu.group.GetGroupListRespone)
  return target;
}

size_t GetGroupListRespone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:youliao.pdu.group.GetGroupListRespone)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .youliao.pdu.base.GroupInfo group_info = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->group_info_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->group_info(static_cast<int>(i)));
    }
  }

  // uint32 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->user_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetGroupListRespone::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:youliao.pdu.group.GetGroupListRespone)
  GOOGLE_DCHECK_NE(&from, this);
  const GetGroupListRespone* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetGroupListRespone>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:youliao.pdu.group.GetGroupListRespone)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:youliao.pdu.group.GetGroupListRespone)
    MergeFrom(*source);
  }
}

void GetGroupListRespone::MergeFrom(const GetGroupListRespone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:youliao.pdu.group.GetGroupListRespone)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  group_info_.MergeFrom(from.group_info_);
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
}

void GetGroupListRespone::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:youliao.pdu.group.GetGroupListRespone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetGroupListRespone::CopyFrom(const GetGroupListRespone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:youliao.pdu.group.GetGroupListRespone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetGroupListRespone::IsInitialized() const {
  return true;
}

void GetGroupListRespone::Swap(GetGroupListRespone* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetGroupListRespone::InternalSwap(GetGroupListRespone* other) {
  using std::swap;
  CastToBase(&group_info_)->InternalSwap(CastToBase(&other->group_info_));
  swap(user_id_, other->user_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetGroupListRespone::GetMetadata() const {
  protobuf_youliao_2egroup_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_youliao_2egroup_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace group
}  // namespace pdu
}  // namespace youliao
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::youliao::pdu::group::GroupCreateRequest* Arena::Create< ::youliao::pdu::group::GroupCreateRequest >(Arena* arena) {
  return Arena::CreateInternal< ::youliao::pdu::group::GroupCreateRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::youliao::pdu::group::GroupCreateRespone* Arena::Create< ::youliao::pdu::group::GroupCreateRespone >(Arena* arena) {
  return Arena::CreateInternal< ::youliao::pdu::group::GroupCreateRespone >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::youliao::pdu::group::GetGroupListRequest* Arena::Create< ::youliao::pdu::group::GetGroupListRequest >(Arena* arena) {
  return Arena::CreateInternal< ::youliao::pdu::group::GetGroupListRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::youliao::pdu::group::GetGroupListRespone* Arena::Create< ::youliao::pdu::group::GetGroupListRespone >(Arena* arena) {
  return Arena::CreateInternal< ::youliao::pdu::group::GetGroupListRespone >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
