// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: youliao.server.proto

#ifndef PROTOBUF_youliao_2eserver_2eproto_INCLUDED
#define PROTOBUF_youliao_2eserver_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "youliao.base.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_youliao_2eserver_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[11];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsValidateRequestImpl();
void InitDefaultsValidateRequest();
void InitDefaultsValidateResponeImpl();
void InitDefaultsValidateRespone();
void InitDefaultsUserOfflineImpl();
void InitDefaultsUserOffline();
void InitDefaultsMsgServerInfoImpl();
void InitDefaultsMsgServerInfo();
void InitDefaultsRouteStatusChangeImpl();
void InitDefaultsRouteStatusChange();
void InitDefaultsRouteGetOnlineFirendRequestImpl();
void InitDefaultsRouteGetOnlineFirendRequest();
void InitDefaultsRouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUseImpl();
void InitDefaultsRouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse();
void InitDefaultsRouteGetOnlineFriendResponeImpl();
void InitDefaultsRouteGetOnlineFriendRespone();
void InitDefaultsRouteBroadcastImpl();
void InitDefaultsRouteBroadcast();
void InitDefaultsGetServerIndexRequestImpl();
void InitDefaultsGetServerIndexRequest();
void InitDefaultsGetServerIndexResponeImpl();
void InitDefaultsGetServerIndexRespone();
inline void InitDefaults() {
  InitDefaultsValidateRequest();
  InitDefaultsValidateRespone();
  InitDefaultsUserOffline();
  InitDefaultsMsgServerInfo();
  InitDefaultsRouteStatusChange();
  InitDefaultsRouteGetOnlineFirendRequest();
  InitDefaultsRouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse();
  InitDefaultsRouteGetOnlineFriendRespone();
  InitDefaultsRouteBroadcast();
  InitDefaultsGetServerIndexRequest();
  InitDefaultsGetServerIndexRespone();
}
}  // namespace protobuf_youliao_2eserver_2eproto
namespace youliao {
namespace pdu {
namespace server {
class GetServerIndexRequest;
class GetServerIndexRequestDefaultTypeInternal;
extern GetServerIndexRequestDefaultTypeInternal _GetServerIndexRequest_default_instance_;
class GetServerIndexRespone;
class GetServerIndexResponeDefaultTypeInternal;
extern GetServerIndexResponeDefaultTypeInternal _GetServerIndexRespone_default_instance_;
class MsgServerInfo;
class MsgServerInfoDefaultTypeInternal;
extern MsgServerInfoDefaultTypeInternal _MsgServerInfo_default_instance_;
class RouteBroadcast;
class RouteBroadcastDefaultTypeInternal;
extern RouteBroadcastDefaultTypeInternal _RouteBroadcast_default_instance_;
class RouteGetOnlineFirendRequest;
class RouteGetOnlineFirendRequestDefaultTypeInternal;
extern RouteGetOnlineFirendRequestDefaultTypeInternal _RouteGetOnlineFirendRequest_default_instance_;
class RouteGetOnlineFriendRespone;
class RouteGetOnlineFriendResponeDefaultTypeInternal;
extern RouteGetOnlineFriendResponeDefaultTypeInternal _RouteGetOnlineFriendRespone_default_instance_;
class RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse;
class RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUseDefaultTypeInternal;
extern RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUseDefaultTypeInternal _RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse_default_instance_;
class RouteStatusChange;
class RouteStatusChangeDefaultTypeInternal;
extern RouteStatusChangeDefaultTypeInternal _RouteStatusChange_default_instance_;
class UserOffline;
class UserOfflineDefaultTypeInternal;
extern UserOfflineDefaultTypeInternal _UserOffline_default_instance_;
class ValidateRequest;
class ValidateRequestDefaultTypeInternal;
extern ValidateRequestDefaultTypeInternal _ValidateRequest_default_instance_;
class ValidateRespone;
class ValidateResponeDefaultTypeInternal;
extern ValidateResponeDefaultTypeInternal _ValidateRespone_default_instance_;
}  // namespace server
}  // namespace pdu
}  // namespace youliao
namespace google {
namespace protobuf {
template<> ::youliao::pdu::server::GetServerIndexRequest* Arena::Create< ::youliao::pdu::server::GetServerIndexRequest>(Arena*);
template<> ::youliao::pdu::server::GetServerIndexRespone* Arena::Create< ::youliao::pdu::server::GetServerIndexRespone>(Arena*);
template<> ::youliao::pdu::server::MsgServerInfo* Arena::Create< ::youliao::pdu::server::MsgServerInfo>(Arena*);
template<> ::youliao::pdu::server::RouteBroadcast* Arena::Create< ::youliao::pdu::server::RouteBroadcast>(Arena*);
template<> ::youliao::pdu::server::RouteGetOnlineFirendRequest* Arena::Create< ::youliao::pdu::server::RouteGetOnlineFirendRequest>(Arena*);
template<> ::youliao::pdu::server::RouteGetOnlineFriendRespone* Arena::Create< ::youliao::pdu::server::RouteGetOnlineFriendRespone>(Arena*);
template<> ::youliao::pdu::server::RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse* Arena::Create< ::youliao::pdu::server::RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse>(Arena*);
template<> ::youliao::pdu::server::RouteStatusChange* Arena::Create< ::youliao::pdu::server::RouteStatusChange>(Arena*);
template<> ::youliao::pdu::server::UserOffline* Arena::Create< ::youliao::pdu::server::UserOffline>(Arena*);
template<> ::youliao::pdu::server::ValidateRequest* Arena::Create< ::youliao::pdu::server::ValidateRequest>(Arena*);
template<> ::youliao::pdu::server::ValidateRespone* Arena::Create< ::youliao::pdu::server::ValidateRespone>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace youliao {
namespace pdu {
namespace server {

// ===================================================================

class ValidateRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.ValidateRequest) */ {
 public:
  ValidateRequest();
  virtual ~ValidateRequest();

  ValidateRequest(const ValidateRequest& from);

  inline ValidateRequest& operator=(const ValidateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ValidateRequest(ValidateRequest&& from) noexcept
    : ValidateRequest() {
    *this = ::std::move(from);
  }

  inline ValidateRequest& operator=(ValidateRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ValidateRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ValidateRequest* internal_default_instance() {
    return reinterpret_cast<const ValidateRequest*>(
               &_ValidateRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ValidateRequest* other);
  friend void swap(ValidateRequest& a, ValidateRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ValidateRequest* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ValidateRequest>(NULL);
  }

  ValidateRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ValidateRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ValidateRequest& from);
  void MergeFrom(const ValidateRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ValidateRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user_name = 1;
  void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  const ::std::string& user_name() const;
  void set_user_name(const ::std::string& value);
  #if LANG_CXX11
  void set_user_name(::std::string&& value);
  #endif
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  ::std::string* mutable_user_name();
  ::std::string* release_user_name();
  void set_allocated_user_name(::std::string* user_name);

  // string user_pwd = 2;
  void clear_user_pwd();
  static const int kUserPwdFieldNumber = 2;
  const ::std::string& user_pwd() const;
  void set_user_pwd(const ::std::string& value);
  #if LANG_CXX11
  void set_user_pwd(::std::string&& value);
  #endif
  void set_user_pwd(const char* value);
  void set_user_pwd(const char* value, size_t size);
  ::std::string* mutable_user_pwd();
  ::std::string* release_user_pwd();
  void set_allocated_user_pwd(::std::string* user_pwd);

  // bytes attach_data = 20;
  void clear_attach_data();
  static const int kAttachDataFieldNumber = 20;
  const ::std::string& attach_data() const;
  void set_attach_data(const ::std::string& value);
  #if LANG_CXX11
  void set_attach_data(::std::string&& value);
  #endif
  void set_attach_data(const char* value);
  void set_attach_data(const void* value, size_t size);
  ::std::string* mutable_attach_data();
  ::std::string* release_attach_data();
  void set_allocated_attach_data(::std::string* attach_data);

  // uint32 msg_serv_id = 3;
  void clear_msg_serv_id();
  static const int kMsgServIdFieldNumber = 3;
  ::google::protobuf::uint32 msg_serv_id() const;
  void set_msg_serv_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.ValidateRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr user_pwd_;
  ::google::protobuf::internal::ArenaStringPtr attach_data_;
  ::google::protobuf::uint32 msg_serv_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsValidateRequestImpl();
};
// -------------------------------------------------------------------

class ValidateRespone : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.ValidateRespone) */ {
 public:
  ValidateRespone();
  virtual ~ValidateRespone();

  ValidateRespone(const ValidateRespone& from);

  inline ValidateRespone& operator=(const ValidateRespone& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ValidateRespone(ValidateRespone&& from) noexcept
    : ValidateRespone() {
    *this = ::std::move(from);
  }

  inline ValidateRespone& operator=(ValidateRespone&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ValidateRespone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ValidateRespone* internal_default_instance() {
    return reinterpret_cast<const ValidateRespone*>(
               &_ValidateRespone_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ValidateRespone* other);
  friend void swap(ValidateRespone& a, ValidateRespone& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ValidateRespone* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ValidateRespone>(NULL);
  }

  ValidateRespone* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ValidateRespone>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ValidateRespone& from);
  void MergeFrom(const ValidateRespone& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ValidateRespone* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user_name = 1;
  void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  const ::std::string& user_name() const;
  void set_user_name(const ::std::string& value);
  #if LANG_CXX11
  void set_user_name(::std::string&& value);
  #endif
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  ::std::string* mutable_user_name();
  ::std::string* release_user_name();
  void set_allocated_user_name(::std::string* user_name);

  // string result_string = 3;
  void clear_result_string();
  static const int kResultStringFieldNumber = 3;
  const ::std::string& result_string() const;
  void set_result_string(const ::std::string& value);
  #if LANG_CXX11
  void set_result_string(::std::string&& value);
  #endif
  void set_result_string(const char* value);
  void set_result_string(const char* value, size_t size);
  ::std::string* mutable_result_string();
  ::std::string* release_result_string();
  void set_allocated_result_string(::std::string* result_string);

  // bytes attach_data = 20;
  void clear_attach_data();
  static const int kAttachDataFieldNumber = 20;
  const ::std::string& attach_data() const;
  void set_attach_data(const ::std::string& value);
  #if LANG_CXX11
  void set_attach_data(::std::string&& value);
  #endif
  void set_attach_data(const char* value);
  void set_attach_data(const void* value, size_t size);
  ::std::string* mutable_attach_data();
  ::std::string* release_attach_data();
  void set_allocated_attach_data(::std::string* attach_data);

  // .youliao.pdu.base.UserInfo user_info = 4;
  bool has_user_info() const;
  void clear_user_info();
  static const int kUserInfoFieldNumber = 4;
  const ::youliao::pdu::base::UserInfo& user_info() const;
  ::youliao::pdu::base::UserInfo* release_user_info();
  ::youliao::pdu::base::UserInfo* mutable_user_info();
  void set_allocated_user_info(::youliao::pdu::base::UserInfo* user_info);

  // uint32 result_code = 2;
  void clear_result_code();
  static const int kResultCodeFieldNumber = 2;
  ::google::protobuf::uint32 result_code() const;
  void set_result_code(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.ValidateRespone)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr result_string_;
  ::google::protobuf::internal::ArenaStringPtr attach_data_;
  ::youliao::pdu::base::UserInfo* user_info_;
  ::google::protobuf::uint32 result_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsValidateResponeImpl();
};
// -------------------------------------------------------------------

class UserOffline : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.UserOffline) */ {
 public:
  UserOffline();
  virtual ~UserOffline();

  UserOffline(const UserOffline& from);

  inline UserOffline& operator=(const UserOffline& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserOffline(UserOffline&& from) noexcept
    : UserOffline() {
    *this = ::std::move(from);
  }

  inline UserOffline& operator=(UserOffline&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserOffline& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserOffline* internal_default_instance() {
    return reinterpret_cast<const UserOffline*>(
               &_UserOffline_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(UserOffline* other);
  friend void swap(UserOffline& a, UserOffline& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserOffline* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<UserOffline>(NULL);
  }

  UserOffline* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<UserOffline>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserOffline& from);
  void MergeFrom(const UserOffline& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserOffline* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.UserOffline)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 user_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsUserOfflineImpl();
};
// -------------------------------------------------------------------

class MsgServerInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.MsgServerInfo) */ {
 public:
  MsgServerInfo();
  virtual ~MsgServerInfo();

  MsgServerInfo(const MsgServerInfo& from);

  inline MsgServerInfo& operator=(const MsgServerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsgServerInfo(MsgServerInfo&& from) noexcept
    : MsgServerInfo() {
    *this = ::std::move(from);
  }

  inline MsgServerInfo& operator=(MsgServerInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgServerInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgServerInfo* internal_default_instance() {
    return reinterpret_cast<const MsgServerInfo*>(
               &_MsgServerInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(MsgServerInfo* other);
  friend void swap(MsgServerInfo& a, MsgServerInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsgServerInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<MsgServerInfo>(NULL);
  }

  MsgServerInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<MsgServerInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsgServerInfo& from);
  void MergeFrom(const MsgServerInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsgServerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // uint32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // uint32 max_conn_count = 3;
  void clear_max_conn_count();
  static const int kMaxConnCountFieldNumber = 3;
  ::google::protobuf::uint32 max_conn_count() const;
  void set_max_conn_count(::google::protobuf::uint32 value);

  // uint32 cur_conn_count = 4;
  void clear_cur_conn_count();
  static const int kCurConnCountFieldNumber = 4;
  ::google::protobuf::uint32 cur_conn_count() const;
  void set_cur_conn_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.MsgServerInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::uint32 port_;
  ::google::protobuf::uint32 max_conn_count_;
  ::google::protobuf::uint32 cur_conn_count_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsMsgServerInfoImpl();
};
// -------------------------------------------------------------------

class RouteStatusChange : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.RouteStatusChange) */ {
 public:
  RouteStatusChange();
  virtual ~RouteStatusChange();

  RouteStatusChange(const RouteStatusChange& from);

  inline RouteStatusChange& operator=(const RouteStatusChange& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RouteStatusChange(RouteStatusChange&& from) noexcept
    : RouteStatusChange() {
    *this = ::std::move(from);
  }

  inline RouteStatusChange& operator=(RouteStatusChange&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RouteStatusChange& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RouteStatusChange* internal_default_instance() {
    return reinterpret_cast<const RouteStatusChange*>(
               &_RouteStatusChange_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RouteStatusChange* other);
  friend void swap(RouteStatusChange& a, RouteStatusChange& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RouteStatusChange* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteStatusChange>(NULL);
  }

  RouteStatusChange* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteStatusChange>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RouteStatusChange& from);
  void MergeFrom(const RouteStatusChange& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RouteStatusChange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // .youliao.pdu.base.UserStatusType user_status_type = 2;
  void clear_user_status_type();
  static const int kUserStatusTypeFieldNumber = 2;
  ::youliao::pdu::base::UserStatusType user_status_type() const;
  void set_user_status_type(::youliao::pdu::base::UserStatusType value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.RouteStatusChange)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 user_id_;
  int user_status_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsRouteStatusChangeImpl();
};
// -------------------------------------------------------------------

class RouteGetOnlineFirendRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.RouteGetOnlineFirendRequest) */ {
 public:
  RouteGetOnlineFirendRequest();
  virtual ~RouteGetOnlineFirendRequest();

  RouteGetOnlineFirendRequest(const RouteGetOnlineFirendRequest& from);

  inline RouteGetOnlineFirendRequest& operator=(const RouteGetOnlineFirendRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RouteGetOnlineFirendRequest(RouteGetOnlineFirendRequest&& from) noexcept
    : RouteGetOnlineFirendRequest() {
    *this = ::std::move(from);
  }

  inline RouteGetOnlineFirendRequest& operator=(RouteGetOnlineFirendRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RouteGetOnlineFirendRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RouteGetOnlineFirendRequest* internal_default_instance() {
    return reinterpret_cast<const RouteGetOnlineFirendRequest*>(
               &_RouteGetOnlineFirendRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(RouteGetOnlineFirendRequest* other);
  friend void swap(RouteGetOnlineFirendRequest& a, RouteGetOnlineFirendRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RouteGetOnlineFirendRequest* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteGetOnlineFirendRequest>(NULL);
  }

  RouteGetOnlineFirendRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteGetOnlineFirendRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RouteGetOnlineFirendRequest& from);
  void MergeFrom(const RouteGetOnlineFirendRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RouteGetOnlineFirendRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes attach_data = 20;
  void clear_attach_data();
  static const int kAttachDataFieldNumber = 20;
  const ::std::string& attach_data() const;
  void set_attach_data(const ::std::string& value);
  #if LANG_CXX11
  void set_attach_data(::std::string&& value);
  #endif
  void set_attach_data(const char* value);
  void set_attach_data(const void* value, size_t size);
  ::std::string* mutable_attach_data();
  ::std::string* release_attach_data();
  void set_allocated_attach_data(::std::string* attach_data);

  // uint32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.RouteGetOnlineFirendRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr attach_data_;
  ::google::protobuf::uint32 user_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsRouteGetOnlineFirendRequestImpl();
};
// -------------------------------------------------------------------

class RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse, 
    ::google::protobuf::uint32, ::google::protobuf::uint32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse, 
    ::google::protobuf::uint32, ::google::protobuf::uint32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    0 > SuperType;
  RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse();
  RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse& other);
  static const RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse*>(&_RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class RouteGetOnlineFriendRespone : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.RouteGetOnlineFriendRespone) */ {
 public:
  RouteGetOnlineFriendRespone();
  virtual ~RouteGetOnlineFriendRespone();

  RouteGetOnlineFriendRespone(const RouteGetOnlineFriendRespone& from);

  inline RouteGetOnlineFriendRespone& operator=(const RouteGetOnlineFriendRespone& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RouteGetOnlineFriendRespone(RouteGetOnlineFriendRespone&& from) noexcept
    : RouteGetOnlineFriendRespone() {
    *this = ::std::move(from);
  }

  inline RouteGetOnlineFriendRespone& operator=(RouteGetOnlineFriendRespone&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RouteGetOnlineFriendRespone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RouteGetOnlineFriendRespone* internal_default_instance() {
    return reinterpret_cast<const RouteGetOnlineFriendRespone*>(
               &_RouteGetOnlineFriendRespone_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(RouteGetOnlineFriendRespone* other);
  friend void swap(RouteGetOnlineFriendRespone& a, RouteGetOnlineFriendRespone& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RouteGetOnlineFriendRespone* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteGetOnlineFriendRespone>(NULL);
  }

  RouteGetOnlineFriendRespone* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteGetOnlineFriendRespone>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RouteGetOnlineFriendRespone& from);
  void MergeFrom(const RouteGetOnlineFriendRespone& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RouteGetOnlineFriendRespone* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, uint32> online_firends = 2;
  int online_firends_size() const;
  void clear_online_firends();
  static const int kOnlineFirendsFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
      online_firends() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
      mutable_online_firends();

  // bytes attach_data = 20;
  void clear_attach_data();
  static const int kAttachDataFieldNumber = 20;
  const ::std::string& attach_data() const;
  void set_attach_data(const ::std::string& value);
  #if LANG_CXX11
  void set_attach_data(::std::string&& value);
  #endif
  void set_attach_data(const char* value);
  void set_attach_data(const void* value, size_t size);
  ::std::string* mutable_attach_data();
  ::std::string* release_attach_data();
  void set_allocated_attach_data(::std::string* attach_data);

  // uint32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.RouteGetOnlineFriendRespone)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      RouteGetOnlineFriendRespone_OnlineFirendsEntry_DoNotUse,
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > online_firends_;
  ::google::protobuf::internal::ArenaStringPtr attach_data_;
  ::google::protobuf::uint32 user_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsRouteGetOnlineFriendResponeImpl();
};
// -------------------------------------------------------------------

class RouteBroadcast : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.RouteBroadcast) */ {
 public:
  RouteBroadcast();
  virtual ~RouteBroadcast();

  RouteBroadcast(const RouteBroadcast& from);

  inline RouteBroadcast& operator=(const RouteBroadcast& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RouteBroadcast(RouteBroadcast&& from) noexcept
    : RouteBroadcast() {
    *this = ::std::move(from);
  }

  inline RouteBroadcast& operator=(RouteBroadcast&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RouteBroadcast& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RouteBroadcast* internal_default_instance() {
    return reinterpret_cast<const RouteBroadcast*>(
               &_RouteBroadcast_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(RouteBroadcast* other);
  friend void swap(RouteBroadcast& a, RouteBroadcast& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RouteBroadcast* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteBroadcast>(NULL);
  }

  RouteBroadcast* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<RouteBroadcast>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RouteBroadcast& from);
  void MergeFrom(const RouteBroadcast& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RouteBroadcast* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 friends = 2;
  int friends_size() const;
  void clear_friends();
  static const int kFriendsFieldNumber = 2;
  ::google::protobuf::uint32 friends(int index) const;
  void set_friends(int index, ::google::protobuf::uint32 value);
  void add_friends(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      friends() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_friends();

  // bytes route_data = 20;
  void clear_route_data();
  static const int kRouteDataFieldNumber = 20;
  const ::std::string& route_data() const;
  void set_route_data(const ::std::string& value);
  #if LANG_CXX11
  void set_route_data(::std::string&& value);
  #endif
  void set_route_data(const char* value);
  void set_route_data(const void* value, size_t size);
  ::std::string* mutable_route_data();
  ::std::string* release_route_data();
  void set_allocated_route_data(::std::string* route_data);

  // uint32 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.RouteBroadcast)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > friends_;
  mutable int _friends_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr route_data_;
  ::google::protobuf::uint32 user_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsRouteBroadcastImpl();
};
// -------------------------------------------------------------------

class GetServerIndexRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.GetServerIndexRequest) */ {
 public:
  GetServerIndexRequest();
  virtual ~GetServerIndexRequest();

  GetServerIndexRequest(const GetServerIndexRequest& from);

  inline GetServerIndexRequest& operator=(const GetServerIndexRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetServerIndexRequest(GetServerIndexRequest&& from) noexcept
    : GetServerIndexRequest() {
    *this = ::std::move(from);
  }

  inline GetServerIndexRequest& operator=(GetServerIndexRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetServerIndexRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetServerIndexRequest* internal_default_instance() {
    return reinterpret_cast<const GetServerIndexRequest*>(
               &_GetServerIndexRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(GetServerIndexRequest* other);
  friend void swap(GetServerIndexRequest& a, GetServerIndexRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetServerIndexRequest* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetServerIndexRequest>(NULL);
  }

  GetServerIndexRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetServerIndexRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetServerIndexRequest& from);
  void MergeFrom(const GetServerIndexRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetServerIndexRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.GetServerIndexRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsGetServerIndexRequestImpl();
};
// -------------------------------------------------------------------

class GetServerIndexRespone : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:youliao.pdu.server.GetServerIndexRespone) */ {
 public:
  GetServerIndexRespone();
  virtual ~GetServerIndexRespone();

  GetServerIndexRespone(const GetServerIndexRespone& from);

  inline GetServerIndexRespone& operator=(const GetServerIndexRespone& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetServerIndexRespone(GetServerIndexRespone&& from) noexcept
    : GetServerIndexRespone() {
    *this = ::std::move(from);
  }

  inline GetServerIndexRespone& operator=(GetServerIndexRespone&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetServerIndexRespone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetServerIndexRespone* internal_default_instance() {
    return reinterpret_cast<const GetServerIndexRespone*>(
               &_GetServerIndexRespone_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(GetServerIndexRespone* other);
  friend void swap(GetServerIndexRespone& a, GetServerIndexRespone& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetServerIndexRespone* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetServerIndexRespone>(NULL);
  }

  GetServerIndexRespone* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetServerIndexRespone>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetServerIndexRespone& from);
  void MergeFrom(const GetServerIndexRespone& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetServerIndexRespone* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:youliao.pdu.server.GetServerIndexRespone)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 index_;
  mutable int _cached_size_;
  friend struct ::protobuf_youliao_2eserver_2eproto::TableStruct;
  friend void ::protobuf_youliao_2eserver_2eproto::InitDefaultsGetServerIndexResponeImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ValidateRequest

// string user_name = 1;
inline void ValidateRequest::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ValidateRequest::user_name() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRequest.user_name)
  return user_name_.GetNoArena();
}
inline void ValidateRequest::set_user_name(const ::std::string& value) {
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRequest.user_name)
}
#if LANG_CXX11
inline void ValidateRequest::set_user_name(::std::string&& value) {
  
  user_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.ValidateRequest.user_name)
}
#endif
inline void ValidateRequest::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.ValidateRequest.user_name)
}
inline void ValidateRequest::set_user_name(const char* value, size_t size) {
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.ValidateRequest.user_name)
}
inline ::std::string* ValidateRequest::mutable_user_name() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRequest.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ValidateRequest::release_user_name() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRequest.user_name)
  
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ValidateRequest::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    
  } else {
    
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRequest.user_name)
}

// string user_pwd = 2;
inline void ValidateRequest::clear_user_pwd() {
  user_pwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ValidateRequest::user_pwd() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRequest.user_pwd)
  return user_pwd_.GetNoArena();
}
inline void ValidateRequest::set_user_pwd(const ::std::string& value) {
  
  user_pwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRequest.user_pwd)
}
#if LANG_CXX11
inline void ValidateRequest::set_user_pwd(::std::string&& value) {
  
  user_pwd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.ValidateRequest.user_pwd)
}
#endif
inline void ValidateRequest::set_user_pwd(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_pwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.ValidateRequest.user_pwd)
}
inline void ValidateRequest::set_user_pwd(const char* value, size_t size) {
  
  user_pwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.ValidateRequest.user_pwd)
}
inline ::std::string* ValidateRequest::mutable_user_pwd() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRequest.user_pwd)
  return user_pwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ValidateRequest::release_user_pwd() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRequest.user_pwd)
  
  return user_pwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ValidateRequest::set_allocated_user_pwd(::std::string* user_pwd) {
  if (user_pwd != NULL) {
    
  } else {
    
  }
  user_pwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_pwd);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRequest.user_pwd)
}

// uint32 msg_serv_id = 3;
inline void ValidateRequest::clear_msg_serv_id() {
  msg_serv_id_ = 0u;
}
inline ::google::protobuf::uint32 ValidateRequest::msg_serv_id() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRequest.msg_serv_id)
  return msg_serv_id_;
}
inline void ValidateRequest::set_msg_serv_id(::google::protobuf::uint32 value) {
  
  msg_serv_id_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRequest.msg_serv_id)
}

// bytes attach_data = 20;
inline void ValidateRequest::clear_attach_data() {
  attach_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ValidateRequest::attach_data() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRequest.attach_data)
  return attach_data_.GetNoArena();
}
inline void ValidateRequest::set_attach_data(const ::std::string& value) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRequest.attach_data)
}
#if LANG_CXX11
inline void ValidateRequest::set_attach_data(::std::string&& value) {
  
  attach_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.ValidateRequest.attach_data)
}
#endif
inline void ValidateRequest::set_attach_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.ValidateRequest.attach_data)
}
inline void ValidateRequest::set_attach_data(const void* value, size_t size) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.ValidateRequest.attach_data)
}
inline ::std::string* ValidateRequest::mutable_attach_data() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRequest.attach_data)
  return attach_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ValidateRequest::release_attach_data() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRequest.attach_data)
  
  return attach_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ValidateRequest::set_allocated_attach_data(::std::string* attach_data) {
  if (attach_data != NULL) {
    
  } else {
    
  }
  attach_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), attach_data);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRequest.attach_data)
}

// -------------------------------------------------------------------

// ValidateRespone

// string user_name = 1;
inline void ValidateRespone::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ValidateRespone::user_name() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRespone.user_name)
  return user_name_.GetNoArena();
}
inline void ValidateRespone::set_user_name(const ::std::string& value) {
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRespone.user_name)
}
#if LANG_CXX11
inline void ValidateRespone::set_user_name(::std::string&& value) {
  
  user_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.ValidateRespone.user_name)
}
#endif
inline void ValidateRespone::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.ValidateRespone.user_name)
}
inline void ValidateRespone::set_user_name(const char* value, size_t size) {
  
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.ValidateRespone.user_name)
}
inline ::std::string* ValidateRespone::mutable_user_name() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRespone.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ValidateRespone::release_user_name() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRespone.user_name)
  
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ValidateRespone::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    
  } else {
    
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRespone.user_name)
}

// uint32 result_code = 2;
inline void ValidateRespone::clear_result_code() {
  result_code_ = 0u;
}
inline ::google::protobuf::uint32 ValidateRespone::result_code() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRespone.result_code)
  return result_code_;
}
inline void ValidateRespone::set_result_code(::google::protobuf::uint32 value) {
  
  result_code_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRespone.result_code)
}

// string result_string = 3;
inline void ValidateRespone::clear_result_string() {
  result_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ValidateRespone::result_string() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRespone.result_string)
  return result_string_.GetNoArena();
}
inline void ValidateRespone::set_result_string(const ::std::string& value) {
  
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRespone.result_string)
}
#if LANG_CXX11
inline void ValidateRespone::set_result_string(::std::string&& value) {
  
  result_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.ValidateRespone.result_string)
}
#endif
inline void ValidateRespone::set_result_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.ValidateRespone.result_string)
}
inline void ValidateRespone::set_result_string(const char* value, size_t size) {
  
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.ValidateRespone.result_string)
}
inline ::std::string* ValidateRespone::mutable_result_string() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRespone.result_string)
  return result_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ValidateRespone::release_result_string() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRespone.result_string)
  
  return result_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ValidateRespone::set_allocated_result_string(::std::string* result_string) {
  if (result_string != NULL) {
    
  } else {
    
  }
  result_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), result_string);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRespone.result_string)
}

// .youliao.pdu.base.UserInfo user_info = 4;
inline bool ValidateRespone::has_user_info() const {
  return this != internal_default_instance() && user_info_ != NULL;
}
inline const ::youliao::pdu::base::UserInfo& ValidateRespone::user_info() const {
  const ::youliao::pdu::base::UserInfo* p = user_info_;
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRespone.user_info)
  return p != NULL ? *p : *reinterpret_cast<const ::youliao::pdu::base::UserInfo*>(
      &::youliao::pdu::base::_UserInfo_default_instance_);
}
inline ::youliao::pdu::base::UserInfo* ValidateRespone::release_user_info() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRespone.user_info)
  
  ::youliao::pdu::base::UserInfo* temp = user_info_;
  user_info_ = NULL;
  return temp;
}
inline ::youliao::pdu::base::UserInfo* ValidateRespone::mutable_user_info() {
  
  if (user_info_ == NULL) {
    user_info_ = ::google::protobuf::Arena::Create< ::youliao::pdu::base::UserInfo >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRespone.user_info)
  return user_info_;
}
inline void ValidateRespone::set_allocated_user_info(::youliao::pdu::base::UserInfo* user_info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(user_info_);
  }
  if (user_info) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      user_info = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRespone.user_info)
}

// bytes attach_data = 20;
inline void ValidateRespone::clear_attach_data() {
  attach_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ValidateRespone::attach_data() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.ValidateRespone.attach_data)
  return attach_data_.GetNoArena();
}
inline void ValidateRespone::set_attach_data(const ::std::string& value) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.ValidateRespone.attach_data)
}
#if LANG_CXX11
inline void ValidateRespone::set_attach_data(::std::string&& value) {
  
  attach_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.ValidateRespone.attach_data)
}
#endif
inline void ValidateRespone::set_attach_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.ValidateRespone.attach_data)
}
inline void ValidateRespone::set_attach_data(const void* value, size_t size) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.ValidateRespone.attach_data)
}
inline ::std::string* ValidateRespone::mutable_attach_data() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.ValidateRespone.attach_data)
  return attach_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ValidateRespone::release_attach_data() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.ValidateRespone.attach_data)
  
  return attach_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ValidateRespone::set_allocated_attach_data(::std::string* attach_data) {
  if (attach_data != NULL) {
    
  } else {
    
  }
  attach_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), attach_data);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.ValidateRespone.attach_data)
}

// -------------------------------------------------------------------

// UserOffline

// uint32 user_id = 1;
inline void UserOffline::clear_user_id() {
  user_id_ = 0u;
}
inline ::google::protobuf::uint32 UserOffline::user_id() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.UserOffline.user_id)
  return user_id_;
}
inline void UserOffline::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.UserOffline.user_id)
}

// -------------------------------------------------------------------

// MsgServerInfo

// string ip = 1;
inline void MsgServerInfo::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MsgServerInfo::ip() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.MsgServerInfo.ip)
  return ip_.GetNoArena();
}
inline void MsgServerInfo::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.MsgServerInfo.ip)
}
#if LANG_CXX11
inline void MsgServerInfo::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.MsgServerInfo.ip)
}
#endif
inline void MsgServerInfo::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.MsgServerInfo.ip)
}
inline void MsgServerInfo::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.MsgServerInfo.ip)
}
inline ::std::string* MsgServerInfo::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.MsgServerInfo.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgServerInfo::release_ip() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.MsgServerInfo.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgServerInfo::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.MsgServerInfo.ip)
}

// uint32 port = 2;
inline void MsgServerInfo::clear_port() {
  port_ = 0u;
}
inline ::google::protobuf::uint32 MsgServerInfo::port() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.MsgServerInfo.port)
  return port_;
}
inline void MsgServerInfo::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.MsgServerInfo.port)
}

// uint32 max_conn_count = 3;
inline void MsgServerInfo::clear_max_conn_count() {
  max_conn_count_ = 0u;
}
inline ::google::protobuf::uint32 MsgServerInfo::max_conn_count() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.MsgServerInfo.max_conn_count)
  return max_conn_count_;
}
inline void MsgServerInfo::set_max_conn_count(::google::protobuf::uint32 value) {
  
  max_conn_count_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.MsgServerInfo.max_conn_count)
}

// uint32 cur_conn_count = 4;
inline void MsgServerInfo::clear_cur_conn_count() {
  cur_conn_count_ = 0u;
}
inline ::google::protobuf::uint32 MsgServerInfo::cur_conn_count() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.MsgServerInfo.cur_conn_count)
  return cur_conn_count_;
}
inline void MsgServerInfo::set_cur_conn_count(::google::protobuf::uint32 value) {
  
  cur_conn_count_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.MsgServerInfo.cur_conn_count)
}

// -------------------------------------------------------------------

// RouteStatusChange

// uint32 user_id = 1;
inline void RouteStatusChange::clear_user_id() {
  user_id_ = 0u;
}
inline ::google::protobuf::uint32 RouteStatusChange::user_id() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteStatusChange.user_id)
  return user_id_;
}
inline void RouteStatusChange::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteStatusChange.user_id)
}

// .youliao.pdu.base.UserStatusType user_status_type = 2;
inline void RouteStatusChange::clear_user_status_type() {
  user_status_type_ = 0;
}
inline ::youliao::pdu::base::UserStatusType RouteStatusChange::user_status_type() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteStatusChange.user_status_type)
  return static_cast< ::youliao::pdu::base::UserStatusType >(user_status_type_);
}
inline void RouteStatusChange::set_user_status_type(::youliao::pdu::base::UserStatusType value) {
  
  user_status_type_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteStatusChange.user_status_type)
}

// -------------------------------------------------------------------

// RouteGetOnlineFirendRequest

// uint32 user_id = 1;
inline void RouteGetOnlineFirendRequest::clear_user_id() {
  user_id_ = 0u;
}
inline ::google::protobuf::uint32 RouteGetOnlineFirendRequest::user_id() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteGetOnlineFirendRequest.user_id)
  return user_id_;
}
inline void RouteGetOnlineFirendRequest::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteGetOnlineFirendRequest.user_id)
}

// bytes attach_data = 20;
inline void RouteGetOnlineFirendRequest::clear_attach_data() {
  attach_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RouteGetOnlineFirendRequest::attach_data() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
  return attach_data_.GetNoArena();
}
inline void RouteGetOnlineFirendRequest::set_attach_data(const ::std::string& value) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
}
#if LANG_CXX11
inline void RouteGetOnlineFirendRequest::set_attach_data(::std::string&& value) {
  
  attach_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
}
#endif
inline void RouteGetOnlineFirendRequest::set_attach_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
}
inline void RouteGetOnlineFirendRequest::set_attach_data(const void* value, size_t size) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
}
inline ::std::string* RouteGetOnlineFirendRequest::mutable_attach_data() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
  return attach_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RouteGetOnlineFirendRequest::release_attach_data() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
  
  return attach_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RouteGetOnlineFirendRequest::set_allocated_attach_data(::std::string* attach_data) {
  if (attach_data != NULL) {
    
  } else {
    
  }
  attach_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), attach_data);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.RouteGetOnlineFirendRequest.attach_data)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RouteGetOnlineFriendRespone

// uint32 user_id = 1;
inline void RouteGetOnlineFriendRespone::clear_user_id() {
  user_id_ = 0u;
}
inline ::google::protobuf::uint32 RouteGetOnlineFriendRespone::user_id() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteGetOnlineFriendRespone.user_id)
  return user_id_;
}
inline void RouteGetOnlineFriendRespone::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteGetOnlineFriendRespone.user_id)
}

// map<uint32, uint32> online_firends = 2;
inline int RouteGetOnlineFriendRespone::online_firends_size() const {
  return online_firends_.size();
}
inline void RouteGetOnlineFriendRespone::clear_online_firends() {
  online_firends_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
RouteGetOnlineFriendRespone::online_firends() const {
  // @@protoc_insertion_point(field_map:youliao.pdu.server.RouteGetOnlineFriendRespone.online_firends)
  return online_firends_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
RouteGetOnlineFriendRespone::mutable_online_firends() {
  // @@protoc_insertion_point(field_mutable_map:youliao.pdu.server.RouteGetOnlineFriendRespone.online_firends)
  return online_firends_.MutableMap();
}

// bytes attach_data = 20;
inline void RouteGetOnlineFriendRespone::clear_attach_data() {
  attach_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RouteGetOnlineFriendRespone::attach_data() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
  return attach_data_.GetNoArena();
}
inline void RouteGetOnlineFriendRespone::set_attach_data(const ::std::string& value) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
}
#if LANG_CXX11
inline void RouteGetOnlineFriendRespone::set_attach_data(::std::string&& value) {
  
  attach_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
}
#endif
inline void RouteGetOnlineFriendRespone::set_attach_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
}
inline void RouteGetOnlineFriendRespone::set_attach_data(const void* value, size_t size) {
  
  attach_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
}
inline ::std::string* RouteGetOnlineFriendRespone::mutable_attach_data() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
  return attach_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RouteGetOnlineFriendRespone::release_attach_data() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
  
  return attach_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RouteGetOnlineFriendRespone::set_allocated_attach_data(::std::string* attach_data) {
  if (attach_data != NULL) {
    
  } else {
    
  }
  attach_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), attach_data);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.RouteGetOnlineFriendRespone.attach_data)
}

// -------------------------------------------------------------------

// RouteBroadcast

// uint32 user_id = 1;
inline void RouteBroadcast::clear_user_id() {
  user_id_ = 0u;
}
inline ::google::protobuf::uint32 RouteBroadcast::user_id() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteBroadcast.user_id)
  return user_id_;
}
inline void RouteBroadcast::set_user_id(::google::protobuf::uint32 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteBroadcast.user_id)
}

// repeated uint32 friends = 2;
inline int RouteBroadcast::friends_size() const {
  return friends_.size();
}
inline void RouteBroadcast::clear_friends() {
  friends_.Clear();
}
inline ::google::protobuf::uint32 RouteBroadcast::friends(int index) const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteBroadcast.friends)
  return friends_.Get(index);
}
inline void RouteBroadcast::set_friends(int index, ::google::protobuf::uint32 value) {
  friends_.Set(index, value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteBroadcast.friends)
}
inline void RouteBroadcast::add_friends(::google::protobuf::uint32 value) {
  friends_.Add(value);
  // @@protoc_insertion_point(field_add:youliao.pdu.server.RouteBroadcast.friends)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
RouteBroadcast::friends() const {
  // @@protoc_insertion_point(field_list:youliao.pdu.server.RouteBroadcast.friends)
  return friends_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
RouteBroadcast::mutable_friends() {
  // @@protoc_insertion_point(field_mutable_list:youliao.pdu.server.RouteBroadcast.friends)
  return &friends_;
}

// bytes route_data = 20;
inline void RouteBroadcast::clear_route_data() {
  route_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RouteBroadcast::route_data() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.RouteBroadcast.route_data)
  return route_data_.GetNoArena();
}
inline void RouteBroadcast::set_route_data(const ::std::string& value) {
  
  route_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:youliao.pdu.server.RouteBroadcast.route_data)
}
#if LANG_CXX11
inline void RouteBroadcast::set_route_data(::std::string&& value) {
  
  route_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:youliao.pdu.server.RouteBroadcast.route_data)
}
#endif
inline void RouteBroadcast::set_route_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  route_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:youliao.pdu.server.RouteBroadcast.route_data)
}
inline void RouteBroadcast::set_route_data(const void* value, size_t size) {
  
  route_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:youliao.pdu.server.RouteBroadcast.route_data)
}
inline ::std::string* RouteBroadcast::mutable_route_data() {
  
  // @@protoc_insertion_point(field_mutable:youliao.pdu.server.RouteBroadcast.route_data)
  return route_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RouteBroadcast::release_route_data() {
  // @@protoc_insertion_point(field_release:youliao.pdu.server.RouteBroadcast.route_data)
  
  return route_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RouteBroadcast::set_allocated_route_data(::std::string* route_data) {
  if (route_data != NULL) {
    
  } else {
    
  }
  route_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), route_data);
  // @@protoc_insertion_point(field_set_allocated:youliao.pdu.server.RouteBroadcast.route_data)
}

// -------------------------------------------------------------------

// GetServerIndexRequest

// -------------------------------------------------------------------

// GetServerIndexRespone

// uint32 index = 1;
inline void GetServerIndexRespone::clear_index() {
  index_ = 0u;
}
inline ::google::protobuf::uint32 GetServerIndexRespone::index() const {
  // @@protoc_insertion_point(field_get:youliao.pdu.server.GetServerIndexRespone.index)
  return index_;
}
inline void GetServerIndexRespone::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:youliao.pdu.server.GetServerIndexRespone.index)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace server
}  // namespace pdu
}  // namespace youliao

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_youliao_2eserver_2eproto_INCLUDED
